language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.1.1
    - android-21
    - extra
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - java -version
  - ./gradlew test

